In [1]:
print('hello')

hello


In [4]:
list1=[1,2,3,4,5]
result=list(map(lambda x:x**3,list1))
print(result)

[1, 8, 27, 64, 125]


In [6]:
list2=[12,67,89,23]
result=list(map(lambda x:x*9/5+32,list2))
print(result)

[53.6, 152.6, 192.2, 73.4]


In [7]:
list2=[12,34,5,6]
total=list(map(lambda x:x**2,list2))
print(total)

[144, 1156, 25, 36]


In [9]:
list3=['gopi','somu','laddi']
total=list(map(lambda x:len(x)*2,list3))
print(total)

[8, 8, 10]


In [17]:
l=['gopi']
result=list(map(lambda x:len(x.upper())**2,l))
print(result)

[16]


In [18]:
num=[1,2,3,4,5,6]
total=list(filter(lambda x:x%3==0 ,num))
print(total)

[3, 6]


In [27]:
num = [1,2,3,4,5,6,7,8,9,10]
total=list(filter(lambda x:x%2==0,num))
print(total)
total1=list(map(lambda x:x**2,total))
print(total1)
total2=list(filter(lambda x:x>20,total1))
print(total2)

[2, 4, 6, 8, 10]
[4, 16, 36, 64, 100]
[36, 64, 100]


In [29]:
name=['nnai','yama','chani','anime']
total=list(filter(lambda x:x.startswith('a'),name))
print(total)

['anime']


In [ ]:
nums=[1,2,30,60,80,90]
total=list(filter(lambda x:x>50,nums))
print(total)

[60, 80, 90]


In [32]:
words = ["cat", "elephant", "dog", "tiger", "bat"]
total=list(filter(lambda x:len(x)>4,words))
print(total)

['elephant', 'tiger']


In [41]:
items = ["apple", "", "banana", "", "cherry"] 
result=list(filter(lambda x:x!="",items))
print(result)

['apple', 'banana', 'cherry']


In [45]:
text = "education"
result=list(filter(lambda x:x in 'aeiou',text))
print(result)

['e', 'u', 'a', 'i', 'o']


In [48]:
from functools import reduce
a=[1,2,3,4,5]
b=reduce(lambda x,y:x+y,a)
print(b)

15


In [52]:
from functools import reduce

a=[1,4,5,6,7,8,9]
b=reduce(lambda x,y:x+y,map(lambda x:x**2,a))
print(b)

272


In [55]:
import math
a=int(input())
print(math.sqrt(a))

9.0


In [57]:
import math
a=float(input())
print(math.ceil(a))
print(math.floor(a))

6
5


In [59]:
import math
r=int(input())
print(math.pi**r)

27551631842.87327


In [60]:
m=math.pow(2,4)
print(m)

16.0


In [64]:
n=math.radians(180)
m=math.degrees(3.141592653589793)
print(n,m)

3.141592653589793 180.0


In [62]:
n1=math.sin(8)
n2=math.cos(9)
n3=math.tan(8)
print(n1,n2,n3)

0.9893582466233818 -0.9111302618846769 -6.799711455220379


In [68]:
m=math.gcd(12,18)
n=math.lcm(8,9)
f=math.factorial(8)
print(m,n,f)

6 72 40320


In [71]:
l=math.log(2,3)
l2=math.log2(2)
print(l,l2)

0.6309297535714574 1.0


In [75]:
l=math.inf
print(l)

inf


In [ ]:
import datetime
a=datetime.datetime.now()
b=datetime.date.today()
c=datetim
print(a,b,c)

2026-06-12 15:32:50.000390 2026-06-12 <class 'datetime.time'>


In [81]:
import datetime
a=datetime.date.today()
b=datetime.time
print(a,b)

2026-06-12 <class 'datetime.time'>


In [86]:
a=datetime.datetime.now()
print(a)
print(a.time())
print(a.date())

2026-06-12 16:46:26.935057
16:46:26.935057
2026-06-12


In [94]:
import datetime
from encodings import ptcp154
a=datetime.date(2020,12,8)
b=datetime.time(12,12,45)
c=datetime.datetime(2020,12,8,12,11,59)
print(a)
print(b)
print(c)

2020-12-08
12:12:45
2020-12-08 12:11:59


In [107]:
import datetime
a=datetime.datetime.now()
print(a.date())
print(a.time())
print(a.year)
print(a.ctime())
print(a.hour)
print(a.month)
print(a.second)
print(a.strftime('%H %M %S'))

2026-06-12
17:09:12.402623
2026
Fri Jun 12 17:09:12 2026
17
6
12
17 09 12


In [102]:
import datetime

d1 = datetime.datetime(2026, 1, 1)
d2 = datetime.datetime(2026, 6, 12)

diff = d2 - d1

print(diff)
print(diff.days)

162 days, 0:00:00
162


In [8]:
import datetime
a=datetime.datetime.now()
b=datetime.date.today()
print(a)
print(b)
print(a.time())

2026-06-12 21:23:23.627312
2026-06-12
21:23:23.627312


In [9]:
import os
print(os.getcwd())

d:\python\genai


In [10]:
print(os.listdir())

['.git', 'basicprogram.ipynb', 'exception.ipynb', 'funtions1.ipynb', 'mat.ipynb', 'matplotlib.ipynb', 'name.py', 'numericalpython.ipynb', 'pandas.ipynb', 'practicewhile.ipynb', 'stringexample.ipynb']


In [15]:
os.mkdir('nani')
# os.makedirs('a/b/c')
os.rmdir('nani')
os.removedirs('a/b/c')

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'a/b/c'

In [40]:
os.rename("matploy.ipynb", "mat.ipynb")

In [ ]:
print(os.path.exists("notes.txt"))
p

False


In [21]:
#import math
from math import sqrt,pi
print(sqrt(7))
print(pi)

2.6457513110645907
3.141592653589793


In [37]:
import random
a=random.randint(1,6)
b=random.random()
c=random.seed()
d=random.uniform(1,20)
print(a,b,c)
print(d)

3 0.7776774955407354 None
10.673062174654415


In [34]:
fruits=['aple','banana','papad']
print(random.choice(fruits))
print(random.choices(fruits))

papad
['banana']


In [ ]:
numbers=[1,2,3,4,5]
random.shuffle(numbers)
print(numbers)

None


In [38]:
import random

names = ["Ravi", "Sita", "Gita", "Mohan"]
print(random.sample(names,3))

['Ravi', 'Mohan', 'Sita']


In [ ]:
# mymodule.py

def greet(name):
    return f"Hello, {name}!"

pi = 3.14159

In [1]:
def nani(name):
    return f'hello,{name}'

print(nani('renu'))

hello,renu


In [4]:
def nani():
    return 'nani'

nani()

'nani'

In [8]:
def greet(name,age):
    return f'hello {name} and my age is {age}'

print(greet('nnai',90))

hello nnai and my age is 90


In [10]:
def house(name,car):
    return f'such a nice {name} and cool {car}'

house(car='thar',name='simpler')

'such a nice simpler and cool thar'

In [12]:
def greet(name,num):
    return f'{name}:{num}'

print(greet(90,'nnai'))

90:nnai


In [14]:
def name(personal='harry',age=12):
    return f'{personal},{age}'


print(name('nani',78))


nani,78


In [15]:
def num(*name):
    return name

print(num('hi','hello','cool','pone'))

('hi', 'hello', 'cool', 'pone')


In [16]:
def num(*numbers):
    return numbers
print(num(1,2,3,4,4,5))

(1, 2, 3, 4, 4, 5)


In [17]:
def student(name,age,course):
    return f'i am {name} and im {age} currently pursuing {course}'

print(student('nani',21,'aids'))

i am nani and im 21 currently pursuing aids


In [18]:
def mul(a,b,c):
    return a*b*c

print(mul(1,2,3))

6


In [19]:
def book(title,author,price):
    return f'this book is {title} and {author} the cose is {price}'

print(book('rise above your arms','somu',2000))

this book is rise above your arms and somu the cose is 2000


In [20]:
def employee(name,id,salary):
    return name,id,salary

employee(id=21,salary=9000,name='renu')

('renu', 21, 9000)

In [21]:
def rectangle(length,width):
    return length*width

print(rectangle(width=90,length=89))

8010


In [22]:
def movie(name,rating,year):
    return name,rating,year

print(movie(rating=9.8,name='21st century girl',year=2023))

('21st century girl', 9.8, 2023)


In [25]:
def greet(name,message='good moeninh'):
    return f'hi {name} and {message}'

print(greet(name='nani'))
print(greet(name='somu',message='hello'))

hi nani and good moeninh
hi somu and hello


In [30]:
def power(number,exponent=3):
    return number**exponent
print(power(2))

8


In [35]:
def discount(amount,discount_rate=10):
    discount_amount= amount*discount_rate/100
    return amount-discount_amount
print(discount(1000))

900.0


In [39]:
def sum_numbers(*numbers):
    total=0
    for i in numbers:
        total+=i
    return total

print(sum_numbers(1,2,3,4))

10


In [42]:
def largest_num(*numbers):
    largest=numbers[0]
    for i in numbers:
        if i>largest:
            largest=i
    return largest

print(largest_num(1,2,3,4,5,9,8,12,1))

12


In [43]:
def avg(*numbers):
    total=0
    for i in numbers:
        total+=i
    return total/len(numbers)

print(avg(1,2,3,4,5))

3.0


In [44]:
def student_info(**deatils):
    return deatils

print(student_info(name='nani',age=21,course='cse'))

{'name': 'nani', 'age': 21, 'course': 'cse'}


In [45]:
def product_details(**price):
    return price 

print(product_details(name='lic',cos=9000,))


{'name': 'lic', 'cos': 9000}


In [46]:
def display_profile(**details):
    return details
print(display_profile(name='nani',age=12))

{'name': 'nani', 'age': 12}


In [47]:
def order(item,quantity=1):
    return item,quantity

print(order(item=21))

(21, 1)


In [49]:
def company(name,**kwargs):
    return name,kwargs
print(company(name='abc',age=90,course='software develpoment'))

('abc', {'age': 90, 'course': 'software develpoment'})


In [52]:
def report(name,age=18,*marks):
    count=0
    for i in marks:
        count+=1
    return name,age,count,count/len(marks)

print(report('anni',90,1,2,3,4,5))


('anni', 90, 5, 1.0)


In [2]:
def shopping_cart(customer,*items,**deails):
    return customer,items,deails

print(shopping_cart('nani',1,2,3,4,5,name='john',age=12,comapny='akruthi'))

('nani', (1, 2, 3, 4, 5), {'name': 'john', 'age': 12, 'comapny': 'akruthi'})


In [8]:
score=0
def add_point():
    global score
    score=score+1

add_point()
print(score)

1


In [9]:
score=0
def add_point(score):
    score=score+1
    return score
add_point(score)
print(score)

0


In [12]:
def num():
    x=10
    print(x)
num()


10


In [14]:
x=10
def num():
    print(x)
num()
print(x)

10
10


In [22]:
x=10
def counter():
    global x
    x=x+1
    print(x)

counter()
counter()
counter()

11
12
13


In [ ]:
x=10
def num():
    x=10
    print(x)
num()
print(x)

10
9


In [26]:
def outer():
    x=10
    def inner():
        print(x)
    inner()
outer()


10


In [28]:
x = 10

def func():
    global x
    print(x)
    x = 20

func()

10


In [29]:
x = 5

def outer():
    x = 10

    def inner():
        x = 15
        print(x)

    inner()
    print(x)

outer()
print(x)

15
10
5


In [33]:



def name():
    message1='hello'
    print(message1)

print(name())
print(message1)

    

hello
None


NameError: name 'message1' is not defined

In [37]:
def countdown(n):
    if n == 0:   # base case
        print("Done!")
        return
    print(n)
    countdown(n - 1)  # recursive call
print(countdown(10))

10
9
8
7
6
5
4
3
2
1
Done!
None


In [40]:
def factorial(n):
    if n==0 or n==1:
        return 1
    return n*factorial(n-1)

print(factorial(5))

120


In [ ]:
def countdown(n):
    if n==0:
        print('done')
        return 
    print(n)
    countdown(n-1)
countdown(5)

5
4
3
2
1
done
None


In [48]:
def summ(n):
    if n==0:
        return 0
    return n+summ(n-1)
print(summ(8))

36


In [49]:
def fact(n):
    if n==0 or n==1:
        return 1
    return n*fact(n-1)

print(fact(4))

24


In [1]:
x=100
def main():
    x=50
    print(x)
main()
print(x)

50
100


In [2]:
def countdown(n):
    if n==0:
        print('done')
        return
    print(n)
    countdown(n-1)
countdown(5)

5
4
3
2
1
done


In [ ]:
def num(n):
    if n==5:
        return
    print(n)
    num(n+1)
    
num(1)

In [5]:
def num(n):
    if n==0:
        return 0
    return n+num(n-1)
    
num(5)

15

In [ ]:
def fibo(n):
    if n==0:
        return 0
    if n==1:
        return 1
    return fibo(n-1)+fibo(n-2)
    
print(fibo(6))

In [ ]:
def sum_of_digits(n):
    if n==0:
        return 0
    return (n%10)+sum_of_digits(n//10)
    
print(sum_of_digits(876456))

In [7]:
import pandas as pd
a={
    'name':['ravi','somu','laskmu'],
    'age':[1,2,3]
}
df=pd.DataFrame(a)
print(df['name'])

0      ravi
1      somu
2    laskmu
Name: name, dtype: object


In [24]:
data={
    'age':[10,20,30,40,50,60,70]
}
df=pd.DataFrame(data)
print(df[df['age']>10])
print(df[(df['age']>20) & (df['age']>40)])
print(df[(df['age']>30) & (df['age']>20)])

   age
1   20
2   30
3   40
4   50
5   60
6   70
   age
4   50
5   60
6   70
   age
3   40
4   50
5   60
6   70


In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [3]:
import numpy as np
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [12]:
a=np.zeros(25)
a=a.reshape(5,5)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
a=np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [23]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [31]:
a=np.array([12, 24, 36, 48, 60])
# print(a.min())
# print(a.max())
# print(a.sum())
# print(a.mean())
# print(a.ndim)
print(np.min(a))

12


In [45]:
a=np.arange(1,17)
b=a.reshape(4,4)
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [48]:
a=np.array([5, 10, 15, 20, 25, 30])
print(a[::-1])
print(np.flip(a))

[30 25 20 15 10  5]
[30 25 20 15 10  5]


In [58]:
import numpy as np
a=np.random.randint(1,100,15)
print(a)
b=a[a>50]
print(b)

[10 12 33 82  4 92 19 67 78 72 31 80 23 42 81]
[82 92 67 78 72 80 81]


In [63]:
a=np.array([-10, 5, -3, 8, -1, 12])
a[a<0]=0
print(a)

[ 0  5  0  8  0 12]


In [65]:
a=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
b=np.transpose(a)
print(b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [66]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [67]:
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [72]:
a=np.zeros(9)
b=a.reshape(3,3)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [73]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [74]:
a=np.array([10, 20, 30, 40, 50])
print(np.flip(a))

[50 40 30 20 10]


In [75]:
a=np.array([-5, 3, -2, 8, -1, 10])
a[a<0]=0
print(a)

[ 0  3  0  8  0 10]


In [77]:
a=np.random.randint(1,100,15)
print(a[a>40])

[48 91 86 72 51 85 89 59 43 48 63 81 75]


In [79]:
a=np.arange(1,17)
b=a.reshape(4,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [81]:
a=np.ones(9)
print(a.reshape(3,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [84]:
a=np.eye(8)
print(a.reshape(8,8))

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [92]:
a=np.arange(1,17).reshape(4,4)
print(np.sum(a,axis=1))
print(np.sum(a[0]))
print(np.max(a,axis=0))
print(np.max(a[0]))
print(a)

[10 26 42 58]
10
[13 14 15 16]
4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
import pandas as pd
a={
    'name':['nani','smou','me','you'],
    'age':[12,34,56,13],
    'marks':[56,89,90,100]
}
df=pd.DataFrame(a)
print(df.info())
print(df.describe())
print(df.columns)
print(df.shape)
print(type(df))
# df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   age     4 non-null      int64 
 2   marks   4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None
            age       marks
count   4.00000    4.000000
mean   28.75000   83.750000
std    20.80665   19.155069
min    12.00000   56.000000
25%    12.75000   80.750000
50%    23.50000   89.500000
75%    39.50000   92.500000
max    56.00000  100.000000
Index(['name', 'age', 'marks'], dtype='object')
(4, 3)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   age     4 non-null      int64 
 2   marks   4 non-null      int64 
dtypes: int64(2), object(1)
memory 

In [108]:
print(df[['name','marks']])
print(df['marks'],df['name'])

   name  marks
0  nani     56
1  smou     89
2    me     90
3   you    100
0     56
1     89
2     90
3    100
Name: marks, dtype: int64 0    nani
1    smou
2      me
3     you
Name: name, dtype: object


In [115]:
df[df['marks']>50]
df['result']=['pass','pass','pass','pass']
print(df)

   name  age  marks result
0  nani   12     56   pass
1  smou   34     89   pass
2    me   56     90   pass
3   you   13    100   pass


In [124]:
df['marks'].mean()
df['marks'].sort_values(ascending=False)

3    100
2     90
1     89
0     56
Name: marks, dtype: int64

In [130]:
import pandas as pd
import numpy as np
data={
    'marks':[12,34,56,78,90,np.nan]
}
df=pd.DataFrame(data)
print(df)
print(df.fillna(0))
print(df.dropna())
df['marks'].max()

   marks
0   12.0
1   34.0
2   56.0
3   78.0
4   90.0
5    NaN
   marks
0   12.0
1   34.0
2   56.0
3   78.0
4   90.0
5    0.0
   marks
0   12.0
1   34.0
2   56.0
3   78.0
4   90.0


np.float64(90.0)

In [17]:
import pandas as pd
data={
    'name':['nani','somu','ravi','rahu','panik'],
    'marks':[12,34,56,78,90]
}
df=pd.DataFrame(data)
print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df['marks'])
print(df['marks'][0:3])
print(df['marks'].iloc[0:3])
print(df.head(3))
print(df['marks']>50)

    name  marks
0   nani     12
1   somu     34
2   ravi     56
3   rahu     78
4  panik     90
(5, 2)
Index(['name', 'marks'], dtype='object')
name     object
marks     int64
dtype: object
0    12
1    34
2    56
3    78
4    90
Name: marks, dtype: int64
0    12
1    34
2    56
Name: marks, dtype: int64
0    12
1    34
2    56
Name: marks, dtype: int64
   name  marks
0  nani     12
1  somu     34
2  ravi     56
0    False
1    False
2     True
3     True
4     True
Name: marks, dtype: bool


In [48]:
import pandas as pd
data={
    'name':['nani','somu','ravi','rahu','panik'],
    'marks':[12,34,56,78,90]
}
df=pd.DataFrame(data)
print(df)
# print(df[df['marks']>75])
# print(df[df['marks']<50])
# df['result']=['fail','fail','pass','pass','pass']
# print(df)
df['result']=df['marks'].apply(lambda x:'pass' if x>50 else 'fail')
print(df)
count=0
for i in df['result']:
    if i=='fail':
        count+=1
print(count)
print(df['result'].value_counts())


    name  marks
0   nani     12
1   somu     34
2   ravi     56
3   rahu     78
4  panik     90
    name  marks result
0   nani     12   fail
1   somu     34   fail
2   ravi     56   pass
3   rahu     78   pass
4  panik     90   pass
2
result
pass    3
fail    2
Name: count, dtype: int64


In [ ]:
import pandas as pd
data={
    'name':['nani','somu','ravi','rahu','panik'],
    'marks':[12,34,56,78,90]
}
df=pd.DataFrame(data)
# print(df)
# print(df.sort_values(by='marks',ascending=True))
# print(df['marks'].mean())
# print(df['marks'].max())
# print(df['marks'].sum())
# print(df['marks'].min())
count=0
for i in df:
    if i[]

    name  marks
0   nani     12
1   somu     34
2   ravi     56
3   rahu     78
4  panik     90
54.0
90
270
12


In [ ]:
import pandas as pd
import numpy as np
data={
    'name':['somu','ravi','harry','appy'],
    'grade':['A','B',np.nan,'C']

}
df=pd.DataFrame(data)
print(df)
print(df.dropna())
print(df.fillna('unknown'))


    name grade
0   somu     A
1   ravi     B
2  harry   NaN
3   appy     C
   name grade
0  somu     A
1  ravi     B
3  appy     C
    name    grade
0   somu        A
1   ravi        B
2  harry  unknown
3   appy        C


In [68]:
import pandas as pd
import numpy as np
data={
    'name':['somu','ravi','harry','appy'],
    'grade':[90,78,26,np.nan]

}
df=pd.DataFrame(data)
print(df)
print(df.dropna())
# print(df.fillna(0))
df['grade']=df['grade'].fillna(df['grade'].mean())
print(df)
df=df.rename(columns={'grade':'score'})
print(df)

    name  grade
0   somu   90.0
1   ravi   78.0
2  harry   26.0
3   appy    NaN
    name  grade
0   somu   90.0
1   ravi   78.0
2  harry   26.0
    name      grade
0   somu  90.000000
1   ravi  78.000000
2  harry  26.000000
3   appy  64.666667
    name      score
0   somu  90.000000
1   ravi  78.000000
2  harry  26.000000
3   appy  64.666667


In [72]:
import pandas as pd

data = {
    'name': ['Somu', 'Ravi', 'Harry', 'Appy', 'Kiran', 'Raju', 'Meena', 'John'],
    'class': ['A', 'A', 'A', 'B', 'B', 'B', 'A', 'B'],
    'marks': [85, 78, 92, 66, 74, 81, 88, 59]
}

df = pd.DataFrame(data)
print(df)
print(df.groupby('class')['marks'].mean())

    name class  marks
0   Somu     A     85
1   Ravi     A     78
2  Harry     A     92
3   Appy     B     66
4  Kiran     B     74
5   Raju     B     81
6  Meena     A     88
7   John     B     59
class
A    85.75
B    70.00
Name: marks, dtype: float64


In [88]:
import pandas as pd

students = ({
    'id': [101, 102, 103, 104, 105],
    'name': ['Somu', 'Ravi', 'Harry', 'Appy', 'Kiran']
})
marks = ({
    'id': [101, 102, 103, 104, 105],
    'marks': [85, 78, 92, 66, 74]
})
df=pd.DataFrame(students)
df1=pd.DataFrame(marks)
# print(df.merge(df1))
print(df.merge(df1,on='id'))
print(df.merge(df1))
print(pd.concat([df,df1],axis=0))

    id   name  marks
0  101   Somu     85
1  102   Ravi     78
2  103  Harry     92
3  104   Appy     66
4  105  Kiran     74
    id   name  marks
0  101   Somu     85
1  102   Ravi     78
2  103  Harry     92
3  104   Appy     66
4  105  Kiran     74
    id   name  marks
0  101   Somu    NaN
1  102   Ravi    NaN
2  103  Harry    NaN
3  104   Appy    NaN
4  105  Kiran    NaN
0  101    NaN   85.0
1  102    NaN   78.0
2  103    NaN   92.0
3  104    NaN   66.0
4  105    NaN   74.0


In [91]:
import pandas as pd

data = {
    'name': ['Somu', 'Ravi', 'Harry', 'Appy', 'Kiran', 'Raju'],
    'marks': [85, 78, 92, 66, 74, 88]
}

df = pd.DataFrame(data)

# Top performer
top = df[df['marks'] == df['marks'].max()]
print("Top performer:")
print(top)

# Second highest
second = df.sort_values(by='marks', ascending=False).iloc[1]
print("\nSecond highest:")
print(second)

Top performer:
    name  marks
2  Harry     92

Second highest:
name     Raju
marks      88
Name: 5, dtype: object
