In [1]:
import numpy as np
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())

150
30.0
50
10
14.142135623730951


In [9]:
arr=np.array([10,20,30,40,50])
print(np.zeros(5))
print(np.ones(8))
print(np.eye(4))
print(np.arange(0,10,2))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0 2 4 6 8]


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.reshape(2,3))
print(type(a))


(2, 3)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [20]:
a=np.array(89)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [21]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[1,2])

6
